spring:
  profiles:
    active: 
     - dev

---
server:
  port: 8002 #配置端口号

#MyBatis配置
mybatis:
  config-location: classpath:/mybatis/mybatis_config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

spring:
  profiles: dev
  application:
    name: microservice-dept
    #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01?characterEncoding=UTF-8
    username: root
    password: 157863
  cloud:
    config:
      discovery:
        enabled: false

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservice-dept8002 #自定义服务名称
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: meta-microservice
  company.name: www.meta.org
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  security:
    enabled: false

---
server:
  port: 8002 #配置端口号

#MyBatis配置
mybatis:
  config-location: classpath:/mybatis/mybatis_config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

spring:
  profiles: test
  application:
    name: microservice-dept
    #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02?characterEncoding=UTF-8
    username: root
    password: 157863
  cloud:
    config:
      discovery:
        enabled: false

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservice-dept8002 #自定义服务名称
    prefer-ip-address: true #访问路径可以显示IP地址

info:
  app.name: meta-microservice
  company.name: www.meta.org
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  security:
    enabled: false