spring:
  profiles:
    avtive:
      - dev

---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: microservice-config-eureka-client

eureka: eurka7001.com
  instance: 
    hostname: 
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

---
server:
  port: 7001

spring:
  profiles: test
  application:
    name: microservice-config-eureka-client

eureka:
  instance: 
    hostname: eureka7001.com
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
